# Generated by Django 2.1.1 on 2018-09-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_auto_20150331_0611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name_plural': 'analyses'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='process_id',
        ),
        migrations.AddField(
            model_name='job',
            name='process',
            field=models.TextField(blank=True, null=True),
        ),
    ]
