# Generated by Django 2.1.2 on 2018-10-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatics', '0003_page_internal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, help_text='The title of the HTML page. You can leave it blank', max_length=300, null=True),
        ),
    ]
